import ReactQueryProviders from '../lib/providers/QueryProvider';
import { Provider } from '@/components/ui/provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>
          <Provider>{children}</Provider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
